# This is a basic workflow to help you get started with Actions

name: Update all Core repositories to new ReadME template

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  updateallrepos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'Jax-Core',
              repo: 'JaxCore',
              workflow_id: 'Dynamic-Readme.yml',
              ref: 'main'
            })
            await github.rest.actions.createWorkflowDispatch({
              owner: 'Jax-Core',
              repo: 'ValliStart',
              workflow_id: 'Dynamic-Readme.yml',
              ref: 'main'
            })
            await github.rest.actions.createWorkflowDispatch({
              owner: 'Jax-Core',
              repo: 'YourMixer',
              workflow_id: 'Dynamic-Readme.yml',
              ref: 'main'
            })
            await github.rest.actions.createWorkflowDispatch({
              owner: 'Jax-Core',
              repo: 'YourFlyouts',
              workflow_id: 'Dynamic-Readme.yml',
              ref: 'main'
            })
            await github.rest.actions.createWorkflowDispatch({
              owner: 'Jax-Core',
              repo: 'Keylaunch',
              workflow_id: 'Dynamic-Readme.yml',
              ref: 'main'
            })
            await github.rest.actions.createWorkflowDispatch({
              owner: 'Jax-Core',
              repo: 'IdleStyle',
              workflow_id: 'Dynamic-Readme.yml',
              ref: 'main'
            })
            await github.rest.actions.createWorkflowDispatch({
              owner: 'Jax-Core',
              repo: 'Plainext',
              workflow_id: 'Dynamic-Readme.yml',
              ref: 'main'
            })
            await github.rest.actions.createWorkflowDispatch({
              owner: 'Jax-Core',
              repo: 'ModularPlayers',
              workflow_id: 'Dynamic-Readme.yml',
              ref: 'main'
            })
            await github.rest.actions.createWorkflowDispatch({
              owner: 'Jax-Core',
              repo: 'ModularClocks',
              workflow_id: 'Dynamic-Readme.yml',
              ref: 'main'
            })
            await github.rest.actions.createWorkflowDispatch({
              owner: 'Jax-Core',
              repo: 'ModularVisualizer',
              workflow_id: 'Dynamic-Readme.yml',
              ref: 'main'
            })
