# This is a basic workflow to help you get started with Actions

name: Update all Core repositories to new ReadME template

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  updateallrepos:
    runs-on: ubuntu-latest
    steps:
      - name: Update repo
        run: |
          curl -XPOST -u "${{ secrets.GIT_CREDENTIALS }}" -H "Accept:application/vnd.github" -H "Content-Type:application/json" https://api.github.com/Jax-Core/ReadME-Test/.github/workflows/Dynamic-ReadME.yml/dispatches --data '{"ref": "main" }'
